# Generated by Django 5.1.7 on 2025-05-04 18:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_directories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subdirectories",
                        to="core.directory",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "parent")},
            },
        ),
        migrations.CreateModel(
            name="Process",
            fields=[
                ("pid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("READY", "Ready"),
                            ("RUNNING", "Running"),
                            ("WAITING", "Waiting"),
                            ("TERMINATED", "Terminated"),
                        ],
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("memory_required", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_run_time", models.DateTimeField(blank=True, null=True)),
                ("quantum", models.IntegerField(default=100)),
                ("priority", models.IntegerField(default=0)),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("DEFAULT", "Default"),
                            ("HACKER", "Hacker"),
                            ("MINER", "Miner"),
                            ("VALIDATOR", "Validator"),
                        ],
                        default="DEFAULT",
                        max_length=20,
                    ),
                ),
                ("page_table", models.JSONField(default=list)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("size", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("is_encrypted", models.BooleanField(default=False)),
                ("permissions", models.JSONField(default=dict)),
                (
                    "directory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.directory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "directory")},
            },
        ),
    ]
