# Generated by Django 5.2 on 2025-04-10 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('READY', 'Ready'), ('RUNNING', 'Running'), ('WAITING', 'Waiting'), ('TERMINATED', 'Terminated')], default='NEW', max_length=20)),
                ('memory_required', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('process_type', models.CharField(choices=[('DEFAULT', 'Default'), ('HACKER', 'Hacker'), ('MINER', 'Miner'), ('VALIDATOR', 'Validator')], default='DEFAULT', max_length=20)),
            ],
        ),
    ]
