# Generated by Django 5.2 on 2025-06-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="process",
            name="alive",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="process",
            name="happiness",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="process",
            name="hunger",
            field=models.IntegerField(default=0),
        ),
    ]
